### ISSUE TITLE
Maybe made a add-on version of it ?

### ISSUE THREAD

**Issue by GGLinnk** [greatis/Anti-WebMiner#13]

**Comment by linuswillner** [comment]
If you mean a browser addon, this method is more efficient because it modifies the Windows hosts file to block requests to blacklisted domains on OS level. This has numerous benefits including the fact that it will work on any browser installed on the system, and it also nullifies PUAs trying to mine crypto on your machine to an extent.

**Comment by greatis** [comment]
Yes. I think about addon version.
Also, I'm going to add Acrylic DNS to support wildcards and do not touch the hosts.
